sudo: required

notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: change
    on_failure: always

language: c

compiler:
  - gcc
  - clang

arch:
    packages:
        - systemd
        - linux-api-headers
        - libdrm
    script:
        - "echo $CC"
        - make debug
        - make DISABLE_FRAME_CAPTURES=1 debug

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

